### ISSUE TITLE
UpToDate and out-of-sync inconsistence

### ISSUE THREAD

**Issue by shutsutsumi** [LINBIT/drbd#30] opened 2022-03-01 05:01 UTC
Hi all,

On drbd-9.0.23 (CentOS 8.2), we are facing an inconsistence of node status. That is, although the state of both DRBD device is UpToDate, there exists some out-of-sync value.

```
#drbdsetup status --verbose --statistics
 r008 node-id:0 role:Primary suspended:no
 write-ordering:flush
 volume:0 minor:8 disk:UpToDate quorum:yes
 size:109757124 read:3065 written:105640 al-writes:27 bm-writes:0
 upper-pending:0 lower-pending:0 al-suspended:no blocked:no
 fs100 node-id:1 connection:Connected role:Secondary congested:no
 ap-in-flight:0 rs-in-flight:0
 volume:0 replication:Established peer-disk:UpToDate
 resync-suspended:no
 received:0 sent:105028 out-of-sync:12 pending:0 unacked:0
```

I see this issue on several systems running drbd-9.0, and I made a stable reproducer (attached for reference). This repeats umount/mount of DRBD disk on primary node, and disconnect/connect on secondary node at the same time.
[drbd-out-of-sync-mountumount.zip](https://github.com/LINBIT/drbd/files/8158834/drbd-out-of-sync-mountumount.zip)

When I run this reproducer on drbd-8.9 for comparison, I never see the issue.
On the other hand, I see this not only drbd-9.0.23, but also the latest 9.1.

Am I doing something wrong or do we have a bug in out-of-sync calculation and state transition to UpToDate?
Any feedback would be greatly appreciated.

**Comment by shutsutsumi** [comment] 2022-03-18 00:52
Hi,all

I am continuing to investigate this.
As a result, I found one fact.

This problem only occurs when the state transitions from "OutDated" to "UpToDate".
And it never occurs when the state transitions from "Inconsistent" to "UpTodate".

Probably,I presume that the state transition from "OutDated" to "UpToDate" 
is not exclusive in the state transition and asynchronous calculation.

Is this a specification? Or is it a bug?
If it's a bug, where in the source code should I add exclusive processing?

I'm worried because I don't know how to fix it.
I would be grateful if anyone could tell me.

**Comment by rck** [comment] 2022-03-21 08:39
Sorry, but 9.0.23 is very very very outdated, I don't think anybody is really up to reproducing bugs in outdated versions that hopefully got fixed in the ~10 releases since then.

**Closed by rck** 2022-03-21 08:39 UTC

**Comment by shutsutsumi** [comment] 2022-03-24 01:26
I have confirmed that this problem can be reproduced with the latest drbd-9.1.16.

> On primary and secondary DRBD devices
> Both states are UpToDate, but there are values ​​that are out of sync.

Any feedback would be greatly appreciated.

**Comment by rck** [comment] 2022-03-24 07:11
Quite frankly last time I only did read up to `9.0.23` and stopped. Now reading the rest of the message: That can be fine. `UpToDate` is based on UUID comparison, `out-of-sync` means there are bits set in the bitmap. You could run a `verify` and check what it has to say

**Comment by shutsutsumi** [comment] 2022-03-25 04:56
I'm sorry, drbd-9.1.6 is correct.

If the state transition is "Outdated"-> "UpToDate", is it necessary to execute the synchronization process?
Because out-of-sync is not 0.

In order to run the synchronization process, it is necessary to issue a new UUID, uuid_compare ()! = 0, and
The synchronization process runs.

**Comment by shutsutsumi** [comment] 2022-03-30 04:22
>UpToDate is based on UUID comparison

Despite the transition to the same UpToDate
Does the UUID change whether it is updated or not depending on the transition source?

If Outdated-> UpToDate, the UUID will not be updated.
If Inconsistent-> UpToDate, the UUID will be updated.

**Comment by shutsutsumi** [comment] 2022-04-06 01:23
I will add to the above comment.

If the UUID is updated, the synchronization process will run,
If the UUID is not updated, the synchronization process will not run.

Therefore, if "Outdated-> UpToDate", the synchronization process will not run.
Doesn't the synchronization process run at the time of this state transition?

I'm worried because I don't know how to fix it.
I would be grateful if anyone could tell me.

**Comment by JoelColledge** [comment] 2022-04-07 08:39
You can find a description of how DRBD UUIDs work [here](https://linbit.com/drbd-user-guide/drbd-guide-9_0-en/#s-gi-tuple). I hope that answers your questions.

As rck mentioned, the `out-of-sync` counter shows how many bits are set in the bitmap. DRBD is cautious in clearing bitmap bits, so it is possible for them to still be set even when the data is actually in sync. Whether a resync occurs is determined by the UUID comparison.

Please compare the data with `verify` or by reading from each node separately. If this shows that there is really inconsistent data, then we are certainly interested in investigating further.

**Comment by shutsutsumi** [comment] 2022-04-13 05:08
Thanks for the reply.
I understand the content.
However, the following two points are doubtful.

1. This does not occur with **DRBD 8.x**
   Is this a specification designed after **DRBD 9.x**?
   Or is it the same specification as **DRBD 8.x**?

2. If you execute verify in this case, you can see that there are unsynchronized blocks.

  When this phenomenon occurs, if you execute the `drbdadm verify` command,
  You can see that asynchronous blocks remain.
  However, it seems strange that the disk status is UpToDate.

Can anyone give us an opinion on the above two points?
